title: "Bootsy" # the name of your site, e.g. ACME Corp.
description: "A Jekyll theme featuring Bootstrap."
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
logo: "/assets/img/logo.png"
favicon: "/assets/img/favicon.ico"
<<<<<<< HEAD
copyright: "&copy; AnsoDesigns.com 2020"
=======
<<<<<<< HEAD
copyright: "&copy; AnsoDesigns.com 2020"
=======
>>>>>>> 3ab68d6e7b0cc65630277589676dfa09dc2a9cf2
>>>>>>> a78b5a5fa0481f9c19343ee96a64e98757f3cc6d

# google_analytics: UA-111111111-1

plugins:
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-sitemap
