title: "Bootsy" # the name of your site, e.g. ACME Corp.
description: "A Jekyll theme featuring Bootstrap."
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
logo: "/assets/img/logo.png"
favicon: "/assets/img/favicon.ico"

# google_analytics: UA-111111111-1

plugins:
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-sitemap
